libdbus:build-require pkg-config
otherwise, configure fails to find libsmack, which
happens to be the first lib searched with pkg-config

  checking for _NSGetEnviron... no
  checking for LIBSMACK... configure: error: libsmack is
  required to enable smack support
  error: Bad exit status from /var/tmp/rpm-tmp.VUiY9N

Change-Id: Ibf01a52ae6274503e2490f835fbd686e985807e8
Signed-off-by: Adrian Negreanu <adrian.m.negreanu@intel.com>